// Code generated by protoc-gen-go. DO NOT EDIT.
// source: url/url.proto

package url // import "github.com/havoc-io/mutagen/pkg/url"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Protocol int32

const (
	Protocol_Local  Protocol = 0
	Protocol_SSH    Protocol = 1
	Protocol_Custom Protocol = 2
)

var Protocol_name = map[int32]string{
	0: "Local",
	1: "SSH",
	2: "Custom",
}
var Protocol_value = map[string]int32{
	"Local":  0,
	"SSH":    1,
	"Custom": 2,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_url_14650a103899002c, []int{0}
}

type URL struct {
	Protocol             Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=url.Protocol" json:"protocol,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Hostname             string   `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Path                 string   `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URL) Reset()         { *m = URL{} }
func (m *URL) String() string { return proto.CompactTextString(m) }
func (*URL) ProtoMessage()    {}
func (*URL) Descriptor() ([]byte, []int) {
	return fileDescriptor_url_14650a103899002c, []int{0}
}
func (m *URL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URL.Unmarshal(m, b)
}
func (m *URL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URL.Marshal(b, m, deterministic)
}
func (dst *URL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URL.Merge(dst, src)
}
func (m *URL) XXX_Size() int {
	return xxx_messageInfo_URL.Size(m)
}
func (m *URL) XXX_DiscardUnknown() {
	xxx_messageInfo_URL.DiscardUnknown(m)
}

var xxx_messageInfo_URL proto.InternalMessageInfo

func (m *URL) GetProtocol() Protocol {
	if m != nil {
		return m.Protocol
	}
	return Protocol_Local
}

func (m *URL) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *URL) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *URL) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *URL) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*URL)(nil), "url.URL")
	proto.RegisterEnum("url.Protocol", Protocol_name, Protocol_value)
}

func init() { proto.RegisterFile("url/url.proto", fileDescriptor_url_14650a103899002c) }

var fileDescriptor_url_14650a103899002c = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0xcd, 0xb2, 0xcd, 0xee, 0x83, 0x4a, 0xf9, 0x4e, 0xc1, 0x53, 0x51, 0x84, 0x3a, 0xb0,
	0x01, 0xfd, 0x07, 0x7a, 0xf1, 0xb0, 0x83, 0x64, 0x78, 0xf1, 0x96, 0x85, 0xd2, 0x0c, 0x93, 0x7d,
	0x25, 0x4d, 0xfc, 0x1d, 0xfe, 0x64, 0x69, 0xdc, 0x7a, 0x7b, 0xdf, 0xe7, 0x79, 0x21, 0xf9, 0xa0,
	0x4c, 0xc1, 0xc9, 0x14, 0x5c, 0x3b, 0x04, 0x8a, 0x84, 0x3c, 0x05, 0x77, 0xf7, 0xcb, 0x80, 0x7f,
	0xaa, 0x1d, 0x3e, 0x42, 0x91, 0xa9, 0x21, 0x27, 0x58, 0xcd, 0x9a, 0x9b, 0xe7, 0xb2, 0x9d, 0xa6,
	0x1f, 0x67, 0xa8, 0x66, 0x8d, 0xb7, 0x50, 0xa4, 0xb1, 0x0b, 0x27, 0xed, 0x3b, 0xb1, 0xa8, 0x59,
	0xb3, 0x51, 0x73, 0x9f, 0x9c, 0xa5, 0x31, 0x66, 0xc7, 0xff, 0xdd, 0xa5, 0x23, 0xc2, 0x72, 0xa0,
	0x10, 0xc5, 0xb2, 0x66, 0x4d, 0xa9, 0x72, 0xce, 0x4c, 0x47, 0x2b, 0x56, 0x79, 0x9b, 0xf3, 0x76,
	0x0b, 0xc5, 0xe5, 0x55, 0xdc, 0xc0, 0x6a, 0x47, 0x46, 0xbb, 0xea, 0x0a, 0xaf, 0x81, 0xef, 0xf7,
	0xef, 0x15, 0x43, 0x80, 0xf5, 0x5b, 0x1a, 0x23, 0xf9, 0x6a, 0xf1, 0xfa, 0xf0, 0x75, 0xdf, 0x1f,
	0xa3, 0x4d, 0x87, 0xd6, 0x90, 0x97, 0x56, 0xff, 0x90, 0x79, 0x3a, 0x92, 0xf4, 0x29, 0xea, 0xbe,
	0x3b, 0xc9, 0xe1, 0xbb, 0x9f, 0x0e, 0x3e, 0xac, 0xf3, 0xe7, 0x5f, 0xfe, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x76, 0xfb, 0xe2, 0x68, 0x02, 0x01, 0x00, 0x00,
}
